name: Build and Push orleans-postgres

on:
  push:
    branches:
      - main
    paths:
      - 'orleans-postgres-docker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'orleans-postgres-docker/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run sparse_checkout.ps1
        working-directory: orleans-postgres-docker
        shell: pwsh
        run:
          pwsh -File sparse-checkout-orleans.ps1 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push orleans-postgres
        uses: docker/build-push-action@v3
        with:
          context: orleans-postgres-docker
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/orleans-postgres:latest